apiVersion: v2
name: jdemetra-new
description: Verkt√∏y for sesongjustering og tidsserie-analyse utviklet i samarbeid med Eurostat.
icon: https://avatars.githubusercontent.com/u/10142886
keywords:
  - JDemetra  # TODO: Change 'home' to link to Dapla Manual
home: https://manual.dapla.ssb.no/statistikkere/jdemetra.html
sources:
  - https://github.com/statisticsnorway/dapla-lab-images
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-services
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3

dependencies:
  - name: library-chart
    version: 4.0.0
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-services
